# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lee's blog
email: blamedrlee@gmail.com
description: "A man's sharing."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lyy1994.github.io" # the base hostname & protocol for your site
twitter_username: blamedrlee
github_username:  lyy1994

# Build settings
markdown: kramdown
